import { Inter, Outfit, Anta } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import { StockProvider } from "@/context/StockContext";
import { CryptoProvider } from "@/context/CryptoContext";
import { AuthProvider } from "@/context/AuthContext";
import { ForexProvider } from "@/context/ForexContext";


const inter = Inter({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-inter",
  subsets: ["latin"],
});

const outfit = Outfit({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-outfit",
});

const anta = Anta({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-anta",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



import StreamChat from "@/components/StreamChat";

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} ${outfit.variable} ${anta.variable} font-inter antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem={false}
          disableTransitionOnChange
        >
          <AuthProvider>
            <StockProvider>
              <CryptoProvider>
                <ForexProvider>
                  {children}
                  <StreamChat />
                </ForexProvider>
              </CryptoProvider>
            </StockProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
